# Valores iniciales de la pantalla. Puedes cambiarlos segun tu entorno.
excel.file.path=${FILE_PATH}
excel.cell.reference=${CELL_REFERENCE}
excel.cell.data-type=NUMERO

monitor.interval.seconds=1

messaging.channel=TELEGRAM
telegram.bot.token=${TOKEN_TELEGRAM}
telegram.chat.id=${CHAT_ID_TELEGRAM}

whatsapp.access-token=${WHATSAPP_TOKEN}
whatsapp.phone-number-id=${WHATSAPP_PHONE_ID}
whatsapp.to=${WHATSAPP_PHONE_NUMBER_TO}
whatsapp.graph-api-version=v25.0

config.external.path=config/application-local.properties
