# Copia este archivo como application-local.properties y coloca tus valores privados.
document.1.file.path=C:\\FinancialProyects\\EstadoFinancieroTest.xlsx
document.1.column=D
document.1.start-row=5
document.1.end-row=20
document.1.data-type=NUMERO
document.1.extra-column-1=J
document.1.extra-label-1=Estado
document.1.extra-column-2=K
document.1.extra-label-2=Ubicacion

document.2.file.path=
document.2.column=
document.2.start-row=1
document.2.end-row=1
document.2.data-type=NUMERO
document.2.extra-column-1=
document.2.extra-label-1=Estado
document.2.extra-column-2=
document.2.extra-label-2=Ubicacion

document.3.file.path=
document.3.column=
document.3.start-row=1
document.3.end-row=1
document.3.data-type=NUMERO
document.3.extra-column-1=
document.3.extra-label-1=Estado
document.3.extra-column-2=
document.3.extra-label-2=Ubicacion

monitor.interval.seconds=1

messaging.channel=TELEGRAM

telegram.bot.token=TU_TOKEN_AQUI
telegram.chat.id=TU_CHAT_ID_AQUI

whatsapp.access-token=TU_ACCESS_TOKEN_AQUI
whatsapp.phone-number-id=TU_PHONE_NUMBER_ID_AQUI
whatsapp.to=524426520700
whatsapp.graph-api-version=v22.0
