# Copia este archivo como application-local.properties y coloca tus valores privados.
#excel.file.path=C:\\FinancialProyects\\EstadoFinancieroTest.xlsx
excel.cell.reference=D5
excel.cell.data-type=NUMERO

monitor.interval.seconds=1

messaging.channel=TELEGRAM

telegram.bot.token=TU_TOKEN_AQUI
telegram.chat.id=TU_CHAT_ID_AQUI

whatsapp.access-token=TU_ACCESS_TOKEN_AQUI
whatsapp.phone-number-id=TU_PHONE_NUMBER_ID_AQUI
whatsapp.to=524426520700
whatsapp.graph-api-version=v22.0
